### ISSUE TITLE
There are a few visualization bugs in cimnet-docs？

### ISSUE THREAD

**Issue by 1335077753** [hxt-tg/cimnet#1]
<img width="1496" alt="WeChat66193c018cb0507ecffb50bdebe4bb18" src="https://user-images.githubusercontent.com/48143206/204079956-5f6ff7c0-beef-47a4-9a9e-d3cdcb458572.png">

Is this a bug or not

**Comment by hxt-tg** [comment]
Thanks for corrections.
This is caused by the upgradation of Sphinx.
I've fixed it and optimized css styles.
